use pavemanacademy;
show tables;
select * from studentrecords;
select studentid, age, sex from studentrecords where Pstatus = 'A' and traveltime >=3;
select studentid, age, sex from studentrecords where Pstatus = 'A' or traveltime >=3;
select studentid, age, sex from studentrecords where (Pstatus = 'A' and traveltime >=3) or (Mjob = 'other');
select studentid, age, sex from studentrecords where Mjob is null;
select studentid, age, sex from studentrecords where Mjob is not null;
select studentid, age, sex from studentrecords where Mjob in('other','teacher');
select studentid, age, sex from studentrecords where g1 between 10 and 15;
Create database HITMANTECHNOLOGY;
use HITMANTECHNOLOGY;
select * from EmployeeData;
select distinct JobRole from EmployeeData;
create table salesEXE select * from EmployeeData where JobRole = 'Sales Executive';
create table RS select * from EmployeeData where JobRole = 'Research Scientist';
create table LT select * from EmployeeData where JobRole = 'Laboratory Technician';
create table MD select * from EmployeeData where JobRole = 'Manufacturing Director';
create table HCR select * from EmployeeData where JobRole = 'Healthcare Representative';
create table MGR select * from EmployeeData where JobRole = 'Manager';
create table SR select * from EmployeeData where JobRole = 'Sales Representative';
create table RD select * from EmployeeData where JobRole = 'Research Director';
create table HR select * from EmployeeData where JobRole = 'Human Resources';

alter table EmployeeData add column Id int not null primary key auto_increment first;
alter table salesexe add column Id int not null primary key auto_increment first;
alter table rs add column Id int not null primary key auto_increment first;
alter table lt add column Id int not null primary key auto_increment first;
alter table md add column Id int not null primary key auto_increment first;
alter table hcr add column Id int not null primary key auto_increment first;
alter table mgr add column Id int not null primary key auto_increment first;
alter table sr add column Id int not null primary key auto_increment first;
alter table rd add column Id int not null primary key auto_increment first;
alter table hr add column Id int not null primary key auto_increment first;
select * from hr;
select * from sr;
# How to join tables
select sr.Age, sr.Attrition, sr.DailyRate, sr.Gender, rd.HourlyRate,rd.JobInvolvement from sr inner Join rd on sr.id = rd.id;
select sr.Age, sr.Attrition, sr.DailyRate, sr.Gender, rd.HourlyRate,rd.JobInvolvement from sr right Join rd on sr.id = rd.id;
select sr.Age, sr.Attrition, sr.DailyRate, sr.Gender, rd.HourlyRate,rd.JobInvolvement from sr left Join rd on sr.id = rd.id;
select sr.Age, sr.Attrition, sr.DailyRate, sr.Gender, rd.HourlyRate,rd.JobInvolvement from sr cross Join rd on sr.id = rd.id;